# file: roles/aws.infrastructure/vars/main.yml
---
#####################################################
# VPC Vars:
#####################################################
region: us-east-1
cidr_block: 172.22.0.0/16
vpc_subnets:
  - cidr: 172.22.1.0/24
    resource_tags: { "Name":"AnsibleTowerSN" }
    az: us-east-1b
route_tables:
  - subnets:
      - 172.22.1.0/24
    routes:
      - dest: 0.0.0.0/0
        gw: igw
        resource_tags: { "Name":"AnsibleTowerRT", "RT" : "Public" }

#####################################################
# Security Group Vars:
#####################################################
security_group: ansible-tower-sg

ansible_tower_sg_rules:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 0.0.0.0/0
rules_egress:
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 0.0.0.0/0

#####################################################
# SSH Key Vars:
#####################################################
ssh_key_path: "{{ lookup('env','HOME') }}/.ssh"

#####################################################
# EC2 Vars:
#####################################################
tower_keypair: tower
tower_instance_type: t2.small #m4.large 
tower_ami: ami-a86614bf  #ami-2051294a
tower_public_ip: yes
tower_instance_tag: tower-demo-server

# LAUNCH TOWER IN AMAZON EC2 (Public Tower Image)
# ------------------------------------------------
# EC2 Region  Location      AMI TYPE  AMI ID    
# us-east-1   N. Virginia   PV        ami-a86614bf
# us-west-1   N. California PV        ami-cdd79aad
# us-west-2   Oregon        PV        ami-028f5e62
# ------------------------------------------------

authorized_tower_ip: 0.0.0.0/0
tower_version: 2.0.0
ansible_ver: 1.7.1

