# file: roles/aws.infrastructure/tasks/main.yml
---

- include: aws_vpc_create.yml
  tags: vpc_create

- include: aws_vpc_delete.yml
  tags: vpc_delete

- include: ec2_instances_create.yml
  tags: ec2_create

- include: ec2_instances_delete.yml
  tags: ec2_delete