# file: aws_infra_terraform.yml
---

# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision AWS Infrastucture using Terraform 
  hosts: local_target
  roles:
  - { role: aws.infra.terraform, tags: ["tf_create"] }



#############################################################
#  USAGE
#############################################################

# ansible-playbook -i inventory/terraform.py aws_infra_terraform.yml --tags "tf_create" 

# ansible-playbook -i inventory/terraform.py aws_infra_terraform.yml --tags "tf_destroy" 
