# file: aws_ec2_instance.yml
---

- name: Configure Ansible Tower 
  hosts: tag_Name_ansible_tower
  tasks: []
  roles:
    - { role: ansible.tower }


#############################################################
#  USAGE
#############################################################

# Using ec2.py to query AWS for your instance by AWS Tags
#
# ansible-playbook -i inventory/ec2.py aws_ec2_instance.yml

# Using terraform.py to target you instance 
#
# ansible-playbook -i inventory/terraform.py aws_ec2_instance.yml