# file: site.yml
---

- name: Provision AWS Infrastucture
  hosts: local_target
  roles:
  # - { role: aws.infrastructure, tags: ["vpc_create"] }
  - { role: aws.cloudformation, tags: ["cf_create"] }



#############################################################
#  USAGE
#############################################################

# ansible-playbook -i inventory site.yml --tags "vpc_create" 

# ansible-playbook -i inventory site.yml --tags "vpc_destroy" 
